[[headers]]
  for = "/ana_junju/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/barberia-premium/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/beleza_pura/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/bella/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/doce_encanto/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/burger/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/burgerdamami/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/burgerdamaura/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/burger-master/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/burger_nova_vida/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/clinica-fontviva/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/cudiodia/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/cold_studio/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/destino-sortudo/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/dizumba_grande/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/eu_meduzu/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/elisandra_elly/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/evolutiva_core/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/franco-francisco/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/jurema-quiosa/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/mdc_gang/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/mano_angola/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/nadira-andrane/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/naotabom/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/prosario/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/piedade-amorim/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/petiscokuyuyu/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/pizzaria_carla/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/pizzaria_sault/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/perfumaria-chik/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sabor-arte/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sabor_pizzaria/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/samerda/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sushi/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/vanilson_gourgel/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/versa/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/wizard/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
